/**
 * Spreadsheet parsing — BRIEF §7.8, SCHEMA.md.
 *
 * The file is read entirely in the browser. Nothing is uploaded, because there
 * is nowhere to upload it to.
 *
 * Two things here are not obvious and both come straight from the real file:
 *
 *  1. **Read the Excel Table, not the used range.** The pack is a queryTable
 *     named `Job_pack` over A1:I443. Columns J-N are empty but carry
 *     formatting, so a naive reader reports 14 columns and five phantom fields.
 *
 *  2. **Every cell is read as text.** `Circuit` holds telephone numbers, and a
 *     numeric coercion silently eats the leading `0`. `raw: false` plus
 *     `defval: ''` gets formatted strings; the seq column is parsed back to a
 *     number explicitly, because it is the only genuine integer.
 */
import type * as XLSXTypes from 'xlsx';
type WorkBook = XLSXTypes.WorkBook;
type WorkSheet = XLSXTypes.WorkSheet;

export interface ParsedSheet {
  readonly sheetName: string;
  readonly headers: string[];
  readonly rows: Array<Record<string, string>>;
  /** True when the rows came from a named Excel Table rather than the used range. */
  readonly fromTable: boolean;
  readonly tableName: string | null;
}

/**
 * SheetJS is ~900KB and is only needed on the import and export screens, so it
 * is dynamically imported (D6). The service worker precaches the chunk, so this
 * still resolves in aeroplane mode.
 */
export async function loadSheetJs(): Promise<typeof XLSXTypes> {
  return import('xlsx');
}

/**
 * Strip a leading apostrophe — SCHEMA.md "Import gotchas".
 *
 * The equipment cells contain a literal `'` in the value itself, not merely an
 * Excel quote-prefix flag, so nothing upstream removes it for us.
 *
 * Only the ends are trimmed: the LLU tie formats contain meaningful internal
 * spaces.
 */
export function cleanCell(value: unknown): string {
  if (value == null) return '';
  let text = typeof value === 'string' ? value : String(value);
  text = text.trim();
  if (text.startsWith("'")) text = text.slice(1).trim();
  return text;
}

interface TableRange {
  readonly name: string;
  readonly ref: string;
}

/**
 * Find the Excel Table definition on a sheet.
 *
 * SheetJS exposes tables inconsistently across versions and file shapes, so try
 * the documented places and fall back to the used range rather than failing —
 * a pack that does not use a table must still import.
 */
function findTable(workbook: WorkBook, sheetName: string): TableRange | null {
  const sheet = workbook.Sheets[sheetName] as (WorkSheet & { '!tables'?: unknown }) | undefined;
  if (!sheet) return null;

  const candidates: unknown[] = [];
  const sheetTables = sheet['!tables'];
  if (Array.isArray(sheetTables)) candidates.push(...sheetTables);

  const workbookTables = (workbook as WorkBook & { Tables?: unknown }).Tables;
  if (Array.isArray(workbookTables)) candidates.push(...workbookTables);

  for (const candidate of candidates) {
    if (candidate === null || typeof candidate !== 'object') continue;
    const record = candidate as Record<string, unknown>;
    const ref = record.ref ?? record.Ref ?? record.range;
    const name = record.name ?? record.Name ?? record.displayName;
    if (typeof ref === 'string' && /^[A-Z]+\d+:[A-Z]+\d+$/.test(ref)) {
      return { name: typeof name === 'string' ? name : 'table', ref };
    }
  }

  return null;
}

/**
 * Make the header names usable as object keys without losing a column.
 *
 * Two things can go wrong in a real pack, and both did in review:
 *
 *  - **Trailing whitespace.** The pack is generated by Power Query, where a
 *    header inheriting a stray space from upstream is routine. Trimming for
 *    display is right; using the trimmed name to *read* the cell is not.
 *  - **Duplicate headers.** Two columns called the same thing would collapse
 *    into one, silently dropping the second.
 *
 * Cells are therefore read by column INDEX (see `parseWorkbook`), and this only
 * produces the display names, disambiguating any repeats.
 */
function uniqueHeaderNames(rawHeaders: string[]): string[] {
  const seen = new Map<string, number>();

  return rawHeaders.map((raw) => {
    const trimmed = String(raw ?? '').trim();
    if (trimmed === '') return '';

    const count = seen.get(trimmed) ?? 0;
    seen.set(trimmed, count + 1);
    // "Ties", then "Ties (2)" — visible in the mapping screen, so he can see
    // that the pack really does have two columns of that name.
    return count === 0 ? trimmed : `${trimmed} (${count + 1})`;
  });
}

/** Drop rows where every cell is empty — trailing formatted rows are common. */
function dropEmptyRows(rows: Array<Record<string, string>>): Array<Record<string, string>> {
  return rows.filter((row) => Object.values(row).some((value) => value !== ''));
}

export async function parseWorkbook(file: ArrayBuffer): Promise<ParsedSheet> {
  const XLSX = await loadSheetJs();

  const workbook = XLSX.read(file, {
    type: 'array',
    // cellText/cellDates off, raw handled per-sheet below. We never want dates
    // coerced — nothing in this pack is a date, and a coerced one would be lost.
    cellDates: false,
    cellNF: false,
    cellStyles: false,
  });

  const sheetName = workbook.SheetNames[0];
  if (sheetName === undefined) throw new ImportError('That file has no worksheets.');

  const sheet = workbook.Sheets[sheetName];
  if (!sheet) throw new ImportError(`Could not read the sheet "${sheetName}".`);

  const table = findTable(workbook, sheetName);

  /*
   * Read as a MATRIX and address cells by column index.
   *
   * The obvious alternative — sheet_to_json's object mode, keyed by header
   * name — has a silent, whole-column failure mode. Its keys are the header
   * cell values *verbatim*; SheetJS does not trim them. Trim the header list
   * for display and then look a cell up by the trimmed name and every lookup
   * on a header carrying a trailing space returns undefined, so that column
   * becomes empty on all 442 rows with nothing reported. The other columns
   * still have values, so the row is not blank and nothing downstream notices.
   *
   * If it landed on `Circuit`, 442 telephone numbers would silently vanish and
   * search-by-circuit — how the office identifies a job to him over the phone —
   * would simply never match. If it landed on `Job Number`, the natural key is
   * destroyed and next week's re-import keeps nothing.
   *
   * Object mode has the same problem with repeated headers, which it renames to
   * `Name_1` behind your back. Indexing by column is immune to both.
   *
   * raw:false + defval:'' still gives formatted strings, which is what keeps
   * the leading 0 on a telephone number.
   */
  const matrix = XLSX.utils.sheet_to_json<unknown[]>(sheet, {
    header: 1,
    raw: false,
    defval: '',
    blankrows: false,
    ...(table !== null ? { range: table.ref } : {}),
  });

  const headerRow = matrix[0];
  if (headerRow === undefined) throw new ImportError('That sheet is empty.');

  // Header order matters: export must round-trip in the source column order.
  const headers = uniqueHeaderNames(headerRow.map((cell) => String(cell ?? '')));

  const rawRows = matrix.slice(1).map((cells) => {
    const row: Record<string, string> = {};
    headers.forEach((header, column) => {
      // A blank header means a column outside the real table — J–N in the real
      // pack are empty but formatted. Skipping them here is what the Excel
      // table range would have done anyway.
      if (header === '') return;
      row[header] = cleanCell(cells[column]);
    });
    return row;
  });

  const rows = dropEmptyRows(rawRows);

  if (rows.length === 0) {
    throw new ImportError('That sheet has a header row but no job rows.');
  }

  return {
    sheetName,
    headers: headers.filter((header) => header !== ''),
    rows,
    fromTable: table !== null,
    tableName: table?.name ?? null,
  };
}

export class ImportError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ImportError';
  }
}
