#!/usr/bin/env node
/**
 * Generate the service worker from the built bundle.
 *
 * Hand-written rather than vite-plugin-pwa (BRIEF §6 allows either, but asks
 * for a readable SW): this is ~60 lines he or his brother can read a year from
 * now, and there is no Workbox runtime to precache on top of the app.
 *
 * Run after `vite build`, so the precache list is the real hashed filenames.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, sep } from 'node:path';

const DIST = process.argv[2] ?? 'dist';
const BASE = process.env.PAIRTRACK_BASE ?? '/';

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const files = walk(DIST)
  .map((file) => relative(DIST, file).split(sep).join('/'))
  .filter((file) => file !== 'sw.js' && !file.endsWith('.map'))
  .sort();

// Everything in dist is precached: the whole app shell, the SheetJS chunk and
// the icons. A day's use must never touch the network (BRIEF §3.2).
const urls = ['', ...files].map((file) => `${BASE}${file}`);

// A content hash over the precache list gives the cache a version that changes
// exactly when the build does — no manual bumping to forget.
const version = createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12);

const sw = `/*
 * PairTrack service worker — generated by scripts/build-sw.mjs. Do not edit.
 *
 * Strategy, in one sentence: precache the entire app on install, then serve
 * every subsequent request from the cache, forever.
 *
 * Offline is the normal case here, not a fallback (BRIEF section 3.4), so there
 * is deliberately no network-first path, no stale-while-revalidate and no
 * "reconnecting" state. A new version arrives only when a new service worker
 * installs, and the page shows an "Update available" bar rather than reloading
 * underneath him mid-job.
 */

const CACHE_PREFIX = 'pairtrack-';
const CACHE = CACHE_PREFIX + '${version}';

const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)),
  );
  // Do NOT skipWaiting: the running page decides when to take the update.
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            // Only OUR old caches. Cache Storage is origin-wide, and on
            // username.github.io every project site of the same user shares
            // that origin — deleting everything that is not ours would wipe
            // the offline cache of unrelated apps.
            .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

function staleAsset() {
  return new Response('Not part of this version of the app. Reload to update.', {
    status: 504,
    headers: { 'Content-Type': 'text/plain' },
  });
}

self.addEventListener('fetch', (event) => {
  const request = event.request;

  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Cross-origin requests should not exist at all — the CSP blocks them — so if
  // one appears, let it fail on its own rather than caching it.
  if (url.origin !== self.location.origin) return;

  // ignoreVary is essential, not a nicety.
  //
  // Many static hosts answer with "Vary: Origin" (vite preview and Cloudflare
  // both do). Cache.match honours Vary, so a response precached by a plain
  // fetch -- which sends no Origin header -- will NOT match the browser's own
  // request for a module script or stylesheet, which is made in CORS mode and
  // DOES send one. The entry sits in the cache and is never found.
  //
  // Online that is invisible, because the miss falls through to the network.
  // Offline it means the app precached perfectly and still refuses to start.
  // The precache is keyed by URL and is entirely ours, so Vary is meaningless
  // for it: ignore it.
  const MATCH = { ignoreVary: true };

  event.respondWith(
    caches.match(request, MATCH).then((cached) => {
      if (cached) return cached;

      // A navigation to any in-app path resolves to the cached shell, so a
      // deep link or a refresh works offline.
      if (request.mode === 'navigate') {
        return caches.match('${BASE}', MATCH).then((shell) => shell || fetch(request));
      }

      // A same-origin asset that missed the cache: try the network, but do not
      // trust an HTML answer.
      //
      // A static host answers an unknown path with index.html. Handing that
      // back for a script request makes the browser reject it with a MIME
      // error that reads like a broken app rather than what it is -- a stale
      // worker asking for a file this version no longer has. Catching it here
      // turns a confusing failure into an accurate one.
      return fetch(request)
        .then((response) => {
          const type = response.headers.get('content-type') || '';
          if (response.ok && type.includes('text/html')) {
            return staleAsset();
          }
          return response;
        })
        .catch(() => staleAsset());
    }),
  );
});

self.addEventListener('message', (event) => {
  // The page sends this when the user taps "Apply" on the update bar.
  if (event.data === 'skip-waiting') self.skipWaiting();
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`sw.js written — cache pairtrack-${version}, ${urls.length} precached URLs`);

// GitHub Pages serves nothing from a directory starting with _ unless this
// exists, and Vite's assets live in /assets — cheap insurance either way.
writeFileSync(join(DIST, '.nojekyll'), '');

// Cloudflare Pages reads _headers. GitHub Pages ignores it; the meta CSP in
// index.html covers that case (BRIEF section 9.7).
const headers = `/*
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; manifest-src 'self'; worker-src 'self' blob:
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: geolocation=(), camera=(), microphone=(), payment=(), usb=()
`;
writeFileSync(join(DIST, '_headers'), headers);
console.log('_headers and .nojekyll written');

// Sanity check: index.html must exist or the shell fallback is a 404.
try {
  readFileSync(join(DIST, 'index.html'));
} catch {
  console.error('build-sw: dist/index.html is missing — did the build run?');
  process.exit(1);
}
